### ISSUE TITLE
inline and inverted seem to do nothing, and how to change the font?

### ISSUE THREAD

**Issue by vesper8** [webformulator/vue3-avatar#1]
First off thanks a lot for making this. I was using vue-avatar and migrated to Vue 3 and that's how I found this library.

I would like to be able to have control of which font is used.. could you add it as a parameter perhaps?

And the other thing, it seems like the inverted and inline parameters have no effect

**Comment by webformulator** [comment]
First off no need to thank me and sorry for reaching you late.
 
Talking of the issues you raised 
**1. inverted has no effect:** You must be using it as 
`<avatar inverted="true|false" />` 

but instead you need to use it as 

`<avatar name="Tony Stark" :inverted="true|false" />`

**2. inline has no effect:** You must be using it as 
`<avatar name="Tony Stark" inline="true|false" />` 

but instead you need to use it as

`<avatar :inline="true|false" />`

I have tested it. To me all looks good.

Note : Maybe your sibling/parent css components will be causing the inline issue.
Tip: Don't use parameters color/background/size/inverted/inline/rounded where you don't want these effects as they are optional and some of them gets triggered with boolean values. So, If you pass any string(without v-bind) even `null`, vue will treat it as `true`.

And Thanks for the suggestion about Font. I will add that soon.

**Comment by iviu23** [comment]
It would be really nice if you could add the `:customStyle` prop as in [vue-avatar](https://github.com/eliep/vue-avatar). I am in the same situation as @vesper8 of migrating our app to Vue3, and being able to customize the font (along with any other CSS properties) is a must for us in order to match the current aesthetics of the UI.

Hope you can finally add it.

Thank you in advance.
